development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: map_maker_development
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: map_maker_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: map_maker_production
  username: map_maker
  password: <%= ENV['MAP_MAKER_DATABASE_PASSWORD'] %>
