
mapping = $ ->
  # Prepare demo data
  data = gon.meta_data
  # Initiate the chart
  $('#container').highcharts 'Map',
    title: text: 'Unemployment Per 100,000 Residents'
    subtitle: text: 'North Carolina 2000'
    mapNavigation:
      enabled: true
      buttonOptions: verticalAlign: 'bottom'
    colorAxis: min: 0
    series: [ {
      data: data
      mapData: Highcharts.maps['countries/us/us-nc-all']
      joinBy: 'hc-key'
      name: 'County'
      states: hover: color: '#888888'
      dataLabels:
        enabled: false
        format: '{point.name}'
    } ]
  return

# ---
# generated by js2coffee 2.1.0
